config/routes.rb
Wedding::Application.routes.draw do

  devise_for :admins, :skip => [:registrations]
  get "home/index"
  root to: 'home#index'
  resources :messages
  resources :guests do
    resources :rsvps, except: [:index]
  end
  resources :rsvps, only: [:index]

  match 'rsvp', to: 'rsvps#enter_rsvp_code', as: :rsvp_code, via: [:get, :post]

  resources :admins do
    collection do
      get 'edit_password'
      patch 'update_password'
    end
  end

  get 'all_admin', to: 'admins#index'

  devise_scope :admin do
    get "admin", to: "devise/sessions#new"
  end
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  before_save :lowercase_custom_rsvp_code

  has_one :rsvp

  validates_presence_of :display_name, :invited_count, :full_name, :custom_rsvp_code
  validates_uniqueness_of :custom_rsvp_code

  def open_plus_one?
    open_plus_one == "yes"
  end

  private

  def lowercase_custom_rsvp_code
    self.custom_rsvp_code.downcase!
  end
end

# == Schema Information
#
# Table name: guests
#
#  id               :integer          not null, primary key
#  display_name     :string(255)
#  invited_count    :integer
#  custom_message   :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#  full_name        :string(255)
#  open_plus_one    :string(255)
#  custom_rsvp_code :string(255)
#

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: [:show, :edit, :update, :destroy]
  layout "admin"

  respond_to :html

  def index
    @guests = Guest.all
    respond_with(@guests)
  end

  def show
    respond_with(@guest)
  end

  def new
    @guest = Guest.new
    respond_with(@guest)
  end

  def edit
  end

  def create
    @guest = Guest.new(guest_params)
    if @guest.save
      respond_with(@guest)
    else
      render :new
    end
  end

  def update
    @guest.update(guest_params)
    respond_with(@guest)
  end

  def destroy
    @guest.destroy
    respond_with(@guest)
  end

  private
    def set_guest
      @guest = Guest.find(params[:id])
    end

    def guest_params
      params.require(:guest).permit(:full_name, :display_name, :invited_count, :custom_message, :custom_rsvp_code)
    end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.haml
= simple_form_for guest do |f|
  = render partial: "shared/form_errors", locals: {record: guest}

  = f.input :full_name
  = f.input :display_name
  = f.input :invited_count
  .hidden= f.input :custom_message
  .hidden= f.input :custom_rsvp_code
  .actions
    = f.button :submit

app/views/guests/edit.html.haml
%h1 Editing Guest
.well
  = render partial: 'form', locals: {guest: @guest}

.links
  = link_to 'Show', @guest
  = link_to 'Back', guests_path

app/views/guests/index.html.haml
%h1 Listing guests

- content_for :top_buttons do
  = link_to "New Guest", new_guest_path, class: top_button_class

%table.table.table-striped.datatable
  %thead
    %tr
      %th Name
      %th Invited Count
      %th RSVP
      %th Actions
  %tbody
    - @guests.each do |guest|
      %tr
        %td= link_to guest.full_name, guest
        %td= guest.invited_count
        %td= guest.rsvp.try(:confirmed_number)
        %td
          .links
            = link_to 'Show', guest
            = link_to 'Edit', edit_guest_path(guest)

app/views/guests/new.html.haml
%h1 New guest
.well
  = render partial: 'form', locals: {guest: @guest}

.links
  = link_to 'Back', guests_path

app/views/guests/show.html.haml
- content_for :top_buttons do
  = link_to "Edit", edit_guest_path(@guest), class: top_button_class
  - if @guest.rsvp.present?
    = link_to "Edit RSVP", edit_guest_rsvp_path(@guest, @guest.rsvp), class: top_button_class
  - else
    = link_to "Create RSVP", new_guest_rsvp_path(@guest), class: top_button_class

%h1= @guest.full_name
.well
  = display_field("Display Name", @guest.display_name)
  = display_field("Invited Count", @guest.invited_count.to_s)
  .hidden= display_field("Custom Message", @guest.custom_message)
  .hidden= display_field("Custom RSVP Code", @guest.custom_rsvp_code)