config/routes.rb
Wedding::Application.routes.draw do

  devise_for :admins, :skip => [:registrations]
  get "home/index"
  root to: 'home#index'
  resources :messages
  resources :guests do
    resources :rsvps, except: [:index]
  end
  resources :rsvps, only: [:index]

  match 'rsvp', to: 'rsvps#enter_rsvp_code', as: :rsvp_code, via: [:get, :post]

  resources :admins do
    collection do
      get 'edit_password'
      patch 'update_password'
    end
  end

  get 'all_admin', to: 'admins#index'

  devise_scope :admin do
    get "admin", to: "devise/sessions#new"
  end
end

app/views/admins/_form.html.haml
= simple_form_for @admin do |f|
  = render partial: "shared/form_errors", locals: {record: @admin}
  = f.input :email
  - if @admin.new_record?
    = f.input :password
    = f.input :password_confirmation
  .actions
    = f.button :submit

app/views/admins/edit.html.haml
%h1 Editing Admin
.well
  = render 'form'

.links
  = link_to 'Show', @admin
  = link_to 'Back', admins_path

app/views/admins/edit_password.html.haml
%h1 Editing Password

.well
  = simple_form_for current_admin, url: { action: "update_password" } do |f|
    - if current_admin.errors.any?
      #error_explanation
        %h2
          = pluralize(current_admin.errors.count, "error")
          prohibited this post from being saved:
        %ul
          - current_admin.errors.full_messages.each do |message|
            %li= message
    = f.input :current_password, hint: "We need your current password to confirm your changes"
    %hr
    = f.input :password, autocomplete: "off"
    = f.input :password_confirmation
    .actions
      = f.button :submit

.links
  = link_to 'Show', current_admin
  = link_to 'Back', all_admin_path

app/views/admins/index.html.haml
- content_for :top_buttons do
  = link_to "New Admin", new_admin_path, class: top_button_class

%h1 Listing Admins
%table.table.table-striped.datatable
  %thead
    %tr
      %th Email
      %th Actions
  %tbody
    - @admins.each do |admin|
      %tr
        %td= link_to admin.email, admin
        %td
          .links.table-links
            = link_to 'Show', admin
            = link_to 'Edit', edit_admin_path(admin)
            - if current_admin == admin
              = link_to 'Update Password', edit_password_admins_path
            = link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' }

app/views/admins/new.html.haml
%h1 New Admin

.well
  = render 'form'
.links
  = link_to 'Back', admins_path

app/views/admins/show.html.haml
%h1= @admin.email
.well
  = display_field("Last Sign In", @admin.last_sign_in_at.to_s)
  = display_field("Created At", @admin.created_at.to_s)
.links
  = link_to 'Edit', edit_admin_path(@admin)
  = link_to 'Back', admins_path