config/routes.rb
Wedding::Application.routes.draw do

  devise_for :admins, :skip => [:registrations]
  get "home/index"
  root to: 'home#index'
  resources :messages
  resources :guests do
    resources :rsvps, except: [:index]
  end
  resources :rsvps, only: [:index]

  match 'rsvp', to: 'rsvps#enter_rsvp_code', as: :rsvp_code, via: [:get, :post]

  resources :admins do
    collection do
      get 'edit_password'
      patch 'update_password'
    end
  end

  get 'all_admin', to: 'admins#index'

  devise_scope :admin do
    get "admin", to: "devise/sessions#new"
  end
end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  belongs_to :guest

  validates_presence_of :guest_id, :confirmed_number, :email

  delegate :invited_count, :full_name, :display_name, :custom_rsvp_code, to: :guest

  def show_custom_message
    if message.present?
      message
    else
      "none"
    end
  end

  def create_message_on_submit
    self.confirmed_number != 0 ?
      "Thanks for submitting your RSVP. We're so excited to celebrate our special day with you!" :
      "Thanks for submitting your RSVP. We'll be thinking of you as you celebrate from afar. Please let us know if your plans change."
  end

  def update_message_on_submit
    self.confirmed_number != 0 ?
      "Thanks for updating your RSVP. We're so excited to celebrate our special day with you!" :
      "Thanks for updating your RSVP. We'll be thinking of you as you celebrate from afar. Please let us know if your plans change."
  end

  def self.total_confirmed_count
    all.map(&:confirmed_number).reduce(:+)
  end

  def self.total_possible_count
    all.map(&:invited_count).reduce(:+)
  end

  def self.percent_responded
    get_percentage(count.to_f / Guest.count)
  end

  def self.attendance_percent
    get_percentage(Rsvp.total_confirmed_count.to_f / Rsvp.total_possible_count)
  end

  def self.get_percentage(number)
    (number * 100).round(1).to_s + "%"
  end

end

# == Schema Information
#
# Table name: rsvps
#
#  id               :integer          not null, primary key
#  guest_id         :integer          not null
#  confirmed_number :integer
#  message          :text
#  email            :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :set_rsvp, only: [:show, :edit, :update, :destroy]
  before_action :set_guest, only: [:show, :edit, :new, :create, :update, :destroy]
  layout "admin"

  respond_to :html

  def index
    @rsvps = Rsvp.all
    respond_with(@rsvps)
  end

  def show
    respond_with(@rsvp)
  end

  def new
    @rsvp = @guest.build_rsvp
    respond_with(@rsvp)
  end

  def edit
  end

  def create
    @rsvp = @guest.build_rsvp(rsvp_params)
    respond_to do |format|
      if @rsvp.save
        if admin_signed_in?
          format.html { redirect_to [@guest, @rsvp], notice: 'RSVP was successfully created.' }
          format.json { render :show, status: :created, location: [@guest, @rsvp] }
        else # guest is submitting RSVP
          NotificationsMailer.rsvp_created(@rsvp.id).deliver
          NotificationsMailer.guest_confirmation(@rsvp.id).deliver if @rsvp.confirmed_number != 0
          format.html { redirect_to root_path, notice: @rsvp.create_message_on_submit }
          format.json { render :show, status: :created, location: [@guest, @rsvp] }
        end
      else
        if admin_signed_in?
          format.html { render :new }
          format.json { render json: @rsvp.errors, status: :unprocessable_entity }
        else
          @rsvp_code = @rsvp.custom_rsvp_code
          flash[:error] = "Oops! Please verify the information below."
          format.html { render :new, layout: "form_only" }
          format.json { render :show, status: :created, location: [@guest, @rsvp] }
        end
      end
    end
  end

  def update
    flash[:notice] = @rsvp.update_message_on_submit if @rsvp.update(rsvp_params)
    if admin_signed_in?
      respond_with([@rsvp.guest, @rsvp])
    else
      NotificationsMailer.rsvp_updated(@rsvp.id).deliver
      redirect_to root_path
    end
  end

  def destroy
    @rsvp.destroy
    redirect_to rsvps_path
  end

  def enter_rsvp_code
    @rsvp_code = params[:rsvp][:custom_rsvp_code].downcase if params[:rsvp] && params[:rsvp][:custom_rsvp_code]

    respond_to do |format|
      if @rsvp_code.present? && @guest = Guest.find_by_custom_rsvp_code(@rsvp_code)
        @show_custom_message = true
        if @guest.rsvp.present?
          @rsvp = @guest.rsvp
          format.html {render :edit, layout: "form_only"}
        else
          @rsvp = @guest.build_rsvp
          format.html {render :new, layout: "form_only"}
        end
      else
        flash[:notice] = "Hmm, we couldn't find your code. Please try entering your RSVP code again." if @rsvp_code.present?
        format.html {render layout: "form_only"}
      end
    end
  end

  private
    def set_rsvp
      @rsvp = Rsvp.find(params[:id])
    end

    def set_guest
      @guest = Guest.find(params[:guest_id])
    end

    def rsvp_params
      params.require(:guest_id)
      params.require(:rsvp).permit(:confirmed_number, :email, :message)
    end
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/views/rsvps/_form.html.haml
- show_custom_message ||= false
.row
  .col-xs-12.col-sm-10.col-sm-offset-1
    %h4.text-center{class: "#{'hidden' unless show_custom_message}"}= custom_message_for(guest)
    .well
      = simple_form_for [guest, rsvp] do |f|
        = render partial: "shared/form_errors", locals: {record: rsvp}
        - hint = guest.open_plus_one? ? "We ask all guests to be above the age of 18" : ""
        = f.input :confirmed_number, label: "How many people are planning to attend?", as: :select, collection: display_possible_guests(guest), input_html: {class: "select2"}, hint: hint
        = f.input :email, label: "Your Email Address:"
        = f.input :message, label: "Send the bride and groom a message (optional)", input_html: {rows: 3}
        .actions
          = f.button :submit, "Submit RSVP", class: "btn-block btn-info btn-lg"
    %h4.text-center.text-muted Don't hesistate to reach out to Emily, Mitch, or the Budde & Nick Families if there's anything else you need.

app/views/rsvps/edit.html.haml
.row
  %div{class: form_class_width}
    .well
      %h2.text-center
        Editing RSVP for
        = @rsvp.display_name
      = render partial: 'form', locals: {rsvp: @rsvp, guest: @guest, show_custom_message: @show_custom_message}

    - if admin_signed_in?
      .links
        = link_to 'Show', [@rsvp.guest, @rsvp]
        = link_to 'Back', rsvps_path

app/views/rsvps/enter_rsvp_code.html.haml
.row
  %div{class: form_class_width}
    .well
      %h1.text-center Enter in your the RSVP Code
      %p.text-center.text-muted Handwritten code with your invite
      = simple_form_for(:rsvp, url: rsvp_code_path, method: :post) do |f|
        = f.input :custom_rsvp_code, label: false, as: :string
        .actions
          = f.button :submit, "Enter Code", class: "btn-block btn-info btn-lg"

app/views/rsvps/index.html.haml
%h1 RSVPs
.well
  = display_calculation("RSVPs", Rsvp.count)
  = display_calculation("Number Coming", Rsvp.total_confirmed_count)
  = display_calculation("Possible Count", Rsvp.total_possible_count)
  = display_calculation("Attendance Percent of RSVPs", Rsvp.attendance_percent)
  = display_calculation("% of total guests RSVP", Rsvp.percent_responded)


%table.table.table-striped.rsvp-datatable
  %thead
    %tr
      %th Updated Date
      %th Name
      %th Confirmed Count
      %th Invited Count
      %th Message
      %th Email
      %th Actions
  %tbody
    - @rsvps.each do |rsvp|
      %tr
        %td= rsvp.updated_at.strftime('%m/%d/%Y')
        %td= link_to rsvp.full_name, [rsvp.guest, rsvp]
        %td= rsvp.confirmed_number
        %td= rsvp.invited_count
        %td= rsvp.message
        %td= rsvp.email
        %td
          .links
            = link_to 'Show', [rsvp.guest, rsvp]
            = link_to 'Edit', edit_guest_rsvp_path(rsvp.guest, rsvp)

app/views/rsvps/new.html.haml
.row
  %div{class: form_class_width}
    .well
      %h2.text-center
        RSVP for
        = @rsvp.display_name
      = render partial: 'form', locals: {rsvp: @rsvp, guest: @guest, show_custom_message: @show_custom_message}

    - if admin_signed_in?
      .links
        = link_to 'Show', @rsvp
        = link_to 'Back', rsvps_path

app/views/rsvps/show.html.haml
- content_for :top_buttons do
  = link_to "Edit", edit_guest_rsvp_path(@guest, @rsvp), class: top_button_class

%h1= @rsvp.display_name
.well
  = display_field("Full Name", @rsvp.full_name)
  = display_field("Confirmed Count", @rsvp.confirmed_number)
  = display_field("Invited Count", @rsvp.invited_count.to_s)
  = display_field("Custom Message", @rsvp.show_custom_message)
  = display_field("Email", @rsvp.email)