config/routes.rb
Wedding::Application.routes.draw do

  devise_for :admins, :skip => [:registrations]
  get "home/index"
  root to: 'home#index'
  resources :messages
  resources :guests do
    resources :rsvps, except: [:index]
  end
  resources :rsvps, only: [:index]

  match 'rsvp', to: 'rsvps#enter_rsvp_code', as: :rsvp_code, via: [:get, :post]

  resources :admins do
    collection do
      get 'edit_password'
      patch 'update_password'
    end
  end

  get 'all_admin', to: 'admins#index'

  devise_scope :admin do
    get "admin", to: "devise/sessions#new"
  end
end

app/views/layouts/_admin_header.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#my-navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Future Nicks
    / Collect the nav links, forms, and other content for toggling
    #my-navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if admin_signed_in?
          %li{role: "presentation"}
            = link_to "Guests", guests_path
          %li{role: "presentation"}
            = link_to "Responses", rsvps_path
          %li{role: "presentation"}
            = link_to "Admin", all_admin_path
          %li{role: "presentation"}
            = link_to "Logout", destroy_admin_session_path, method: "delete"
        - else
          %li{role: "presentation"}
            = link_to "Log In", new_admin_session_path

app/views/layouts/_header_contents.html.haml
%title Future Nicks - Emily and Mitch's Wedding
%meta{name: "description", content: "Mitch Nick and Emily Budde get ready to celebrate their wedding on July 25th 2015."}
%meta{name: "keywords", content: "Mitchell Nick, Mitch Nick, Emily Budde, Emily Nick, Minneapolis Wedding, Minneaoplis Web Developer Wedding"}
%meta{name: "viewport", content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"}

%link{:href => "https://fonts.googleapis.com/css?family=Dancing+Script:700", :rel => "stylesheet"}/
%link{:href => "https://fonts.googleapis.com/css?family=EB+Garamond", :rel => "stylesheet"}/
%link{:href => "https://fonts.googleapis.com/css?family=Raleway:900", :rel => "stylesheet"}/

%script{:src => "https://maps.google.com/maps/api/js?key=AIzaSyBSk93K-AFD5AMNA--mtmn4GB_voGjWvyc"}
%script{:src => "https://cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"}
%script{:src => "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js", :type => "text/javascript"}

-# %script{:src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyBSk93K-AFD5AMNA--mtmn4GB_voGjWvyc", :type => "text/javascript"}
= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
= javascript_include_tag "application", "data-turbolinks-track" => true
= csrf_meta_tags

%link{:rel=>"icon", :type=>"image/png", :href=>"assets/favicon-16x16.png", :sizes=>"16x16"}
%link{:rel=>"icon", :type=>"image/png", :href=>"assets/favicon-32x32.png", :sizes=>"32x32"}
%link{:rel=>"icon", :type=>"image/png", :href=>"assets/favicon-72x72.png", :sizes=>"72x72"}

app/views/layouts/admin.html.haml
!!!
%html
  %head
    = render partial: "layouts/header_contents"
  %body#admin
    = render partial: 'layouts/admin_header'
    = render partial: 'shared/flash', locals: {flash: flash}
    #admin-containter.row
      - if content_for? :top_buttons
        .text-right.top-buttons
          = content_for :top_buttons
      .col-xs-12
        = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render partial: "layouts/header_contents"
  %body{"data-spy" => "scroll", "data-target" => ".navbar-default"}
    = yield

app/views/layouts/form_only.html.haml
!!!
%html
  %head
    = render partial: "layouts/header_contents"
  %body#admin
    %nav.navbar.navbar-default
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#my-navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "/"} Future Nicks
        / Collect the nav links, forms, and other content for toggling

    = render partial: 'shared/flash', locals: {flash: flash}
    %section#rsvp= yield